# Generated by Django 2.0.1 on 2018-01-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='activation',
        ),
        migrations.RemoveField(
            model_name='model',
            name='hidden_layer_sizes',
        ),
        migrations.RemoveField(
            model_name='model',
            name='solver',
        ),
        migrations.AddField(
            model_name='predictions',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predictions',
            name='actual',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predictions',
            name='yesterday',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
