# Generated by Django 2.0.1 on 2018-01-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20180115_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='train_rsquared',
        ),
        migrations.AlterField(
            model_name='model',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
