# Generated by Django 2.0.1 on 2018-01-16 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20180115_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
    ]
