# Generated by Django 2.0.1 on 2018-01-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_delete_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=0)),
                ('test_rsquared', models.FloatField(default=0)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
